# --- Window Settings ---
# window_title ""

# Set background opacity 
background_opacity 0.90

# Remove window decorations
# hide_window_decorations yes
window_padding_width 1

# --- Font Settings ---
# Set the primary font family and size.
font_family JetBrainsMono Nerd Font
font_size 14.0

# --- Cursor Settings ---
shell_integration no-cursor
cursor_shape block
cursor_trail 0

# --- Theme ---
# Catppuccin-Mocha
# include themes/catppuccin-mocha.conf
# Follow noctalia global theme
tab_bar_edge top
include themes/noctalia.conf
# Modify default tab to make it similar to tmux
tab_title_template " {index}: {title} "
active_tab_title_template " {index}: {title} "
tab_bar_style separator
tab_separator " "


# --- Multiplexer Control keybindings ---

# ============================================================
# Kitty tmux-like configuration
# ============================================================

# Make splits available
enabled_layouts splits,stack

# ============================================================
# Pane splitting
# ============================================================

# Leader + -
map ctrl+space>- launch --location=hsplit --cwd=current

# Leader + \
map ctrl+space>\ launch --location=vsplit --cwd=current


# ============================================================
# Pane navigation - Vim style
# ============================================================

map ctrl+space>h neighboring_window left
map ctrl+space>j neighboring_window down
map ctrl+space>k neighboring_window up
map ctrl+space>l neighboring_window right


# ============================================================
# Close pane
# ============================================================

map ctrl+space>x close_window


# ============================================================
# Zoom pane
# ============================================================

map ctrl+space>z toggle_layout stack


# ============================================================
# New tab
# ============================================================

map ctrl+space>c new_tab


# ============================================================
# Tabs 1-9
# ============================================================

map ctrl+space>1 goto_tab 1
map ctrl+space>2 goto_tab 2
map ctrl+space>3 goto_tab 3
map ctrl+space>4 goto_tab 4
map ctrl+space>5 goto_tab 5
map ctrl+space>6 goto_tab 6
map ctrl+space>7 goto_tab 7
map ctrl+space>8 goto_tab 8
map ctrl+space>9 goto_tab 9


# ============================================================
# Resize panes
# ============================================================

map ctrl+space>shift+h resize_window narrower
map ctrl+space>shift+J resize_window shorter
map ctrl+space>shift+K resize_window taller
map ctrl+space>shift+L resize_window wider
